# CircleCI Configuration for Continuous Integration and Deployment
version: 3.0

# Define stable versions of browsers to be used in tests
chrome-stable-version: &chrome-stable-version "133.0.6943.141"
chrome-beta-version: &chrome-beta-version "134.0.6998.35"
firefox-stable-version: &firefox-stable-version "135.0"

# Define reusable components (orbs)
orbs:
  browser-tools: circleci/browser-tools@1.5.2

# Default settings applied to all jobs
defaults: &defaults
  parallelism: 1
  working_directory: ~/cypress
  parameters: &defaultsParameters
    executor: cy-doc
    only-cache-for-root-user: false
  executor: <<parameters.executor>>
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York" # Set timezone
    CIRCLE_ARTIFACTS: /tmp/artifacts # Store artifacts here
    COLUMNS: 100 # Terminal width
    LINES: 24 # Terminal height

# Branch filters for main build process
mainBuildFilters: &mainBuildFilters
  filters:
    branches:
      only:
        - develop
        - /^release\/\d+\.\d+\.\d+$/
        - feat/implement_bidi
        - 'update-v8-snapshot-cache-on-develop'
        - 'ryanm/chore/add_internal_studio'

# Mac workflow filters for conditional builds
macWorkflowFilters: &darwin-workflow-filters
  when:
    or:
      - equal: [ develop, << pipeline.git.branch >> ]
      - equal: [ 'update-v8-snapshot-cache-on-develop', << pipeline.git.branch >> ]
      - equal: [ 'feat/implement_bidi', << pipeline.git.branch >> ]
      - matches:
          pattern: /^release\/\d+\.\d+\.\d+$/
          value: << pipeline.git.branch >>

# Define executors for different environments
executors:
  # Executor for Linux with Cypress dependencies
  cy-doc:
    docker:
      - image: cypress/base-internal:20.18.1-bullseye
    resource_class: medium
    environment:
      PLATFORM: linux
      CI_DOCKER: "true"

  # Other executors can be defined similarly...

# Commands to be executed during the CI/CD process
commands:
  # Set up environment variable for persisting artifacts
  setup_should_persist_artifacts:
    steps:
      - run:
          name: Set environment variable for artifacts persistence
          command: |
            echo "Setting SHOULD_PERSIST_ARTIFACTS variable"
            echo 'if ! [[ "$CIRCLE_BRANCH" != "develop" && "$CIRCLE_BRANCH" != "release/"* && "$CIRCLE_BRANCH" != "feat/implement_bidi" ]]; then
                export SHOULD_PERSIST_ARTIFACTS=true
            fi' >> "$BASH_ENV"
  
  # Verify if artifacts should be persisted
  verify_should_persist_artifacts:
    steps:
      - run:
          name: Verify persistence of artifacts
          command: |
            if [[ -z "$SHOULD_PERSIST_ARTIFACTS" ]]; then
              echo "Not uploading artifacts or posting install comment for this branch."
              circleci-agent step halt
            fi

  # Additional commands...

# Jobs to be executed in the CI/CD process
jobs:
  # Job for installing node modules
  node_modules_install:
    <<: *defaults
    resource_class: medium
    steps:
      - update_known_hosts
      - checkout
      - install-required-node
      - verify-build-setup:
          executor: << parameters.executor >>
      - persist_to_workspace:
          root: ~/
          paths:
            - cypress
            - .ssh
            - .nvm # Mac/Linux
            - ProgramData/nvm # Windows
      - caching-dependency-installer:
          only-cache-for-root-user: <<parameters.only-cache-for-root-user>>
  
  # Job for building the application
  build:
    <<: *defaults
    steps:
      - restore_cached_workspace
      - run:
          name: Build application
          command: yarn build
      - store-npm-logs
      - persist_to_workspace:
          root: ~/
          paths:
            - cypress

  # Additional jobs...

# Define workflows to group jobs
workflows:
  version: 2
  linux-x64:
    <<: [ *linux-x64-workflow, *linux-x64-workflow-exclude-filters ]
  # Additional workflows...